image: ruby:3.1.2

before_script:
  - ruby -v
  - bundle install --jobs $(nproc)
  # download captain
  - arch=x86_64 # Supported values are x86_64 or aarch64
  - os=linux # Supported values are linux or darwin
  - tmp="$(mktemp -d)/captain"
  - curl -o $tmp -fsSL "https://releases.captain.build/v1/$os/$arch/captain"
  - install $tmp /usr/local/bin
  - rm $tmp
  - captain --version

rspec:
  script:
    - captain run captain-examples-rspec
  artifacts:
    when: always
    paths:
      - tmp/junit.xml
    reports:
      junit: tmp/junit.xml

rspec-with-retries:
  script:
    - captain run captain-examples-rspec-retries
  artifacts:
    when: always
    paths:
      - tmp/junit.xml
    reports:
      junit: tmp/junit.xml

rspec-with-partitioning:
  parallel: 2
  script:
    - suite_id="captain-examples-rspec"
    - test_files=$(
      captain partition
      --suite-id $suite_id
      --index $((CI_NODE_INDEX-1))
      --total $CI_NODE_TOTAL
      "spec/**/*_spec.rb"
      )
    - captain run $suite_id -- $test_files
  artifacts:
    when: always
    paths:
      - tmp/junit.xml
    reports:
      junit: tmp/junit.xml

rspec-with-partitioning-and-retries:
  parallel: 2
  script:
    - suite_id="captain-examples-rspec-retries"
    - test_files=$(
      captain partition
      --suite-id $suite_id
      --index $((CI_NODE_INDEX-1))
      --total $CI_NODE_TOTAL
      "spec/**/*_spec.rb"
      )
    - captain run $suite_id -- $test_files

  artifacts:
    when: always
    paths:
      - tmp/junit.xml
    reports:
      junit: tmp/junit.xml
