test-suites:
  captain-examples-rspec:
    command: bundle exec rspec --format json --out tmp/rspec.json --format progress
    results:
      path: tmp/rspec.json
    output:
      reporters:
        junit-xml: tmp/junit.xml

  captain-examples-rspec-partition:
    results:
      path: tmp/rspec.json
    output:
      reporters:
        junit-xml: tmp/junit.xml
    partition:
      command: bundle exec rspec --format json --out tmp/rspec.json --format progress {{ testFiles }}
      globs:
        - spec/**/*_spec.rb

  captain-examples-rspec-retries:
    command: bundle exec rspec --format json --out tmp/rspec.json --format progress
    results:
      path: tmp/rspec.json
    output:
      print-summary: true
      reporters:
        junit-xml: tmp/junit.xml
    retries:
      attempts: 2
      command: bundle exec rspec --format json --out tmp/rspec.json --format progress {{ tests }}

  captain-examples-rspec-partition-retries:
    results:
      path: tmp/rspec.json
    output:
      print-summary: true
      reporters:
        junit-xml: tmp/junit.xml
    retries:
      attempts: 2
      command: bundle exec rspec --format json --out tmp/rspec.json --format progress {{ tests }}
    partition:
      command: bundle exec rspec --format json --out tmp/rspec.json --format progress {{ testFiles }}
      globs:
        - spec/**/*_spec.rb
